name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1.11.0
        with:
          swift-version: "5.5.0"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-NSAbout-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-NSAbout
      - name: Build
        run: swift build
      - name: Test
        run: swift test
